--- # Master playbook for DataRobot Assessment 


# Setup and Start of mongoDB
- hosts: all
  connection: local
  become: yes
  become_method: sudo
  gather_facts: true 
  roles:
  - MongoDBSetup

# Python Setup: installs pip, then flask and various flask plugins, then starts the flask app
- hosts: all
  connection: local
  become: yes
  become_method: sudo
  gather_facts: true 
  roles:
  - WebAppSetup