--- # Main task list for Inital Setup

- name: Install Python Pip
  apt:
    name: python-pip
    state: latest

#- name: Install Virtual Env
#  apt:
#    name: python-virtualenv
#    state; latest

- name: install flask with Pip
  pip:
    name: flask

- name: install Flask-RESTful
  pip:
    name: flask-restful

- name: install Flask-PyMongo
  pip:
    name: Flask-PyMongo

- name: Start Flask App
  script: /vagrant/roles/WebAppSetup/files/app.py
