--- # Main task list for Inital Setup

- name: Install Python Pip
  apt:
    name: python-pip
    state: latest

#- name: Install Virtual Env
#  apt:
#    name: python-virtualenv
#    state; latest

- name: install flask with Pip
  pip:
    name: flask

- name: install Flask-RESTful
  pip:
    name: flask-restful

- name: install pymongo
  pip:
    name: pymongo

- name: install dateutil
  pip:
    name: python-dateutil

- name: install gunicorn
  pip:
    name: gunicorn

- name: copy Upstart Configuration
  copy:
    src: webapp.conf
    dest: /etc/init

- name: start server service
  service:
    name: webapp
    state: started