--- # Main task list for Inital Setup

- name: Install Python Pip
  apt:
    name: python-pip
    state: latest

#- name: Install Virtual Env
#  apt:
#    name: python-virtualenv
#    state; latest

- name: install flask with Pip
  pip:
    name: flask

- name: install Flask-RESTful
  pip:
    name: flask-restful

- name: install pymongo
  pip:
    name: pymongo

- name: install dateutil
  pip:
    name: python-dateutil

- name: Start Flask App
  shell: python /vagrant/roles/WebAppSetup/files/app.py
